export let dummyFootballFields = [
    {
        id: 1,
        name: 'Soccerdome Wien20',
        latitude: 48.2469922,
        longitude: 16.3700908,
        description: 'Traglufthalle mit Kunstrasenplätzen',
        rating: 4.3,
        image: 'https://www.soccerdome.at/wp-content/uploads/2020/09/DSC_0424.jpg',
        isFavorite: true,
        address: '1200 Wien, Hopsagasse 6',
        indoorOutdoor: true,
        size: 40,
        showerFacilities: false,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 2,
        name: 'Sportzentrum Marswiese',
        latitude: 48.2395836,
        longitude: 16.2751437,
        description: 'Großer Kunstrasenplatz + Halle',
        rating: 4.6,
        image: 'https://im-graetzl-production.s3.eu-central-1.amazonaws.com/shrine/store/1d297781d5f087ce0b575ee2a3447ed6.jpg',
        isFavorite: true,
        address: '1170 Wien, Neuwaldegger Str. 57A',
        indoorOutdoor: false,
        size: 60,
        showerFacilities: true,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 3,
        name: 'Westside Soccer Arena',
        latitude: 48.20003,
        longitude: 16.26428,
        description: 'In- und Outdoor Kunstrasenplätze im Westen Wiens',
        rating: 4.4,
        image: 'https://www.b2soccer.de/wp-content/uploads/2016/02/Sportoase.jpg',
        isFavorite: true,
        address: '1140 Wien, Bahnhofstraße 1D',
        indoorOutdoor: true,
        size: 50,
        showerFacilities: false,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 4,
        name: 'Football Field D',
        latitude: 48.212,
        longitude: 16.340,
        description: 'Well-maintained field for all ages.',
        rating: 3,
        image: 'https://img0.oastatic.com/img2/18748106/600x300c/variant.jpg',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: false,
        size: 30,
        showerFacilities: true,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 5,
        name: 'Football Field E',
        latitude: 48.214,
        longitude: 16.350,
        description: 'Family-friendly football spot.',
        rating: 2.8,
        image: 'https://tourism.seefeld.com/media/infrastructure/fussballplatz-3.jpg',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: true,
        size: 35,
        showerFacilities: false,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 6,
        name: 'Football Field F',
        latitude: 48.170,
        longitude: 16.376,
        description: 'Energetic atmosphere during matches.',
        rating: 4.1,
        image: 'https://www.kitzbueheler-alpen.com/feratel/info/large/westendorf-fussballplatz-westendorfer-waldstadion-fussballplatz.jpg',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: true,
        size: 40,
        showerFacilities: false,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 7,
        name: 'Football Field G',
        latitude: 48.166,
        longitude: 16.344,
        description: 'Training ground with modern facilities.',
        rating: 3.5,
        image: 'https://www.ksv-wien.at/ksvcms/wp-content/uploads/2018/08/fussball-1-1500x630.jpg',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: true,
        size: 40,
        showerFacilities: false,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 8,
        name: 'Football Field H',
        latitude: 48.188,
        longitude: 16.360,
        description: 'Cozy field for casual games.',
        rating: 4,
        image: 'https://isoled.info/wp-content/uploads/2021/01/lichtanlagen-led-sportplaetze-fussball-isoled-at-1k.jpg',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: true,
        size: 40,
        showerFacilities: false,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 9,
        name: 'Football Field I',
        latitude: 48.194,
        longitude: 16.3735,
        description: 'Youth-friendly soccer space.',
        rating: 2,
        image: 'https://www.paznaun-ischgl.com/deskline/infrastruktur/objekte/fussballplatz-see_173811/image-thumb__54044179__hero-slide-small/Fu%C3%9Fballplatz_55994861.jpg',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: true,
        size: 40,
        showerFacilities: true,
        parking: true,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    },
    {
        id: 10,
        name: 'Football Field J',
        latitude: 48.230,
        longitude: 16.390,
        description: 'Modern stadium for major events.',
        rating: 3.8,
        image: 'https://www.gemeinde.bruneck.bz.it/system/web/GetImage.ashx?fileid=976293&mode=T&width=500&height=500&cts=1568195045',
        isFavorite: false,
        address: '1120 Wien, Teststraße 123',
        indoorOutdoor: true,
        size: 40,
        showerFacilities: true,
        parking: false,
        contact: {phone: +436601234567, mail: 'fake@fakemail.at'}
    }
];